# Generated by Django 5.2.15 on 2026-06-11 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('business_category', models.CharField(blank=True, choices=[('commerce', 'Comércio'), ('service', 'Serviço'), ('food', 'Alimentação'), ('beauty', 'Beleza'), ('health', 'Saúde'), ('technology', 'Tecnologia'), ('education', 'Educação'), ('other', 'Outros')], max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=8)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('address_complement', models.CharField(blank=True, max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('ibge_code', models.CharField(blank=True, max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('suspended', 'Suspensa'), ('canceled', 'Cancelada')], default='active', max_length=20)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('collaborator', 'Colaborador')], max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Convidado'), ('active', 'Ativo'), ('inactive', 'Inativo'), ('revoked', 'Revogado')], default='invited', max_length=20)),
                ('invite_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('last_access_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_membership_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__business_name', 'invite_email'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['cnpj'], name='organizatio_cnpj_970e63_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='organizatio_status_295901_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_c6aad1_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['invite_email'], name='organizatio_invite__712398_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('organization', 'user'), name='unique_membership_per_user_organization'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'invited')), fields=('organization', 'invite_email'), name='unique_pending_invite_per_email_organization'),
        ),
    ]
