# Generated by Django 5.2.15 on 2026-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cnae_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='cnae_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='mei_opt_in',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='organization',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
