# Generated by Django 5.2.15 on 2026-06-11 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('viacep', 'ViaCEP'), ('brasil_api_cnpj', 'BrasilAPI CNPJ'), ('awesome_api_exchange', 'AwesomeAPI Câmbio'), ('das_mei_simulated', 'DAS MEI Simulado'), ('firebase_cloud_messaging', 'Firebase Cloud Messaging')], max_length=40)),
                ('http_method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failure', 'Falha')], max_length=20)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_service_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_service_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', 'status'], name='integration_service_4cb11a_idx'), models.Index(fields=['organization', 'created_at'], name='integration_organiz_d56fae_idx')],
            },
        ),
    ]
