# Generated by Django 5.2.15 on 2026-06-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalservicelog',
            name='service',
            field=models.CharField(choices=[('viacep', 'ViaCEP'), ('brasil_api_cnpj', 'BrasilAPI CNPJ'), ('awesome_api_exchange', 'AwesomeAPI Câmbio'), ('das_mei_simulated', 'DAS MEI Simulado'), ('firebase_cloud_messaging', 'Firebase Cloud Messaging'), ('google_oauth', 'Google OAuth')], max_length=40),
        ),
    ]
