# Generated by Django 5.2.15 on 2026-08-09 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('organizations', '0002_organization_cnae_code_organization_cnae_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('create', 'Criar'), ('update', 'Editar'), ('delete', 'Excluir')], max_length=20)),
                ('entity_type', models.CharField(choices=[('payable', 'Conta a pagar'), ('receivable', 'Conta a receber'), ('revenue', 'Entrada'), ('expense', 'Saída'), ('customer', 'Cliente'), ('supplier', 'Fornecedor')], max_length=20)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_version', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Aguardando confirmação'), ('confirmed', 'Confirmada'), ('canceled', 'Cancelada'), ('expired', 'Expirada'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_actions', to='chatbot.chatmessage')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='chatbot.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_actions', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['organization', 'user', 'status'], name='chatbot_pen_organiz_e2264c_idx'), models.Index(fields=['conversation', 'created_at'], name='chatbot_pen_convers_83b98e_idx')],
            },
        ),
    ]
