# Generated by Django 5.2.15 on 2026-06-11 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DasTaxGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Vencido')], default='pending', max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('proof_document_id', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='das_tax_guides', to='organizations.organization')),
            ],
            options={
                'ordering': ['-reference_month'],
                'indexes': [models.Index(fields=['organization', 'status'], name='tax_dastaxg_organiz_d3961a_idx'), models.Index(fields=['due_date'], name='tax_dastaxg_due_dat_546a30_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'reference_month'), name='unique_das_tax_guide_per_month')],
            },
        ),
    ]
